name: allusis
favicon: null
layout_spectrum: 0.5927799495402724
typography_spectrum: 0.0216192367952317
title: Allusis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9798652650788426
  lightness: 0.9585414759349078
  saturation: 0.42996565042994916
  rhythmicContrast: 0.9657824405003339
purpose: []
